### PR TITLE
Add Redux DevTools support

### PR DESCRIPTION
**Pull request by abraham**

### CODE REVIEW

**Comment by sdirix** [comment]
Thanks for your contribution.

Is there a specific reason to avoid adding `redux-devtools-extension` as a dependency and using its convenience functions?

**Comment by abraham** [comment]
The only downside that I know of is an additional dependency. It is less code change though.

**Comment by sdirix** [comment]
Thanks! We'll take a look

**Comment by abraham** [comment]
`devToolsEnhancer` types require an argument.

**Pull request merged**
